package org.example.cayenne.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.example.cayenne.persistent.Division;
import org.example.cayenne.persistent.Facilitator;

/**
 * Class _Competition was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Competition extends CayenneDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String DIVISIONS_PROPERTY = "divisions";
    public static final String JUDGES_PROPERTY = "judges";

    public static final String ID_PK_COLUMN = "ID";

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void addToDivisions(Division obj) {
        addToManyTarget(DIVISIONS_PROPERTY, obj, true);
    }
    public void removeFromDivisions(Division obj) {
        removeToManyTarget(DIVISIONS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Division> getDivisions() {
        return (List<Division>)readProperty(DIVISIONS_PROPERTY);
    }


    public void addToJudges(Facilitator obj) {
        addToManyTarget(JUDGES_PROPERTY, obj, true);
    }
    public void removeFromJudges(Facilitator obj) {
        removeToManyTarget(JUDGES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Facilitator> getJudges() {
        return (List<Facilitator>)readProperty(JUDGES_PROPERTY);
    }


}
