package org.example.cayenne.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.example.cayenne.persistent.Division;
import org.example.cayenne.persistent.EventRoster;

/**
 * Class _Event was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Event extends CayenneDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String DIVISION_PROPERTY = "division";
    public static final String JUDGE_PROPERTY = "judge";

    public static final String ID_PK_COLUMN = "ID";

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setDivision(Division division) {
        setToOneTarget(DIVISION_PROPERTY, division, true);
    }

    public Division getDivision() {
        return (Division)readProperty(DIVISION_PROPERTY);
    }


    public void addToJudge(EventRoster obj) {
        addToManyTarget(JUDGE_PROPERTY, obj, true);
    }
    public void removeFromJudge(EventRoster obj) {
        removeToManyTarget(JUDGE_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<EventRoster> getJudge() {
        return (List<EventRoster>)readProperty(JUDGE_PROPERTY);
    }


}
