package org.example.cayenne.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.example.cayenne.persistent.Event;
import org.example.cayenne.persistent.Facilitator;

/**
 * Class _EventRoster was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EventRoster extends CayenneDataObject {

    public static final String EVENT_ID_PROPERTY = "eventId";
    public static final String FACILITATOR_ID_PROPERTY = "facilitatorId";
    public static final String EVENT_PROPERTY = "event";
    public static final String FACILITATOR_PROPERTY = "facilitator";

    public static final String ID_PK_COLUMN = "ID";

    public void setEventId(Integer eventId) {
        writeProperty(EVENT_ID_PROPERTY, eventId);
    }
    public Integer getEventId() {
        return (Integer)readProperty(EVENT_ID_PROPERTY);
    }

    public void setFacilitatorId(Integer facilitatorId) {
        writeProperty(FACILITATOR_ID_PROPERTY, facilitatorId);
    }
    public Integer getFacilitatorId() {
        return (Integer)readProperty(FACILITATOR_ID_PROPERTY);
    }

    public void addToEvent(Event obj) {
        addToManyTarget(EVENT_PROPERTY, obj, true);
    }
    public void removeFromEvent(Event obj) {
        removeToManyTarget(EVENT_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Event> getEvent() {
        return (List<Event>)readProperty(EVENT_PROPERTY);
    }


    public void addToFacilitator(Facilitator obj) {
        addToManyTarget(FACILITATOR_PROPERTY, obj, true);
    }
    public void removeFromFacilitator(Facilitator obj) {
        removeToManyTarget(FACILITATOR_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Facilitator> getFacilitator() {
        return (List<Facilitator>)readProperty(FACILITATOR_PROPERTY);
    }


}
