package org.example.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.example.cayenne.persistent.Event;

/**
 * Class _SchoolScores was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SchoolScores extends CayenneDataObject {

    public static final String SCHOOL_NAME_PROPERTY = "schoolName";
    public static final String SCHOOL_SCORE_PROPERTY = "schoolScore";
    public static final String EVENT_PROPERTY = "event";

    public static final String ID_PK_COLUMN = "ID";

    public void setSchoolName(String schoolName) {
        writeProperty(SCHOOL_NAME_PROPERTY, schoolName);
    }
    public String getSchoolName() {
        return (String)readProperty(SCHOOL_NAME_PROPERTY);
    }

    public void setSchoolScore(Integer schoolScore) {
        writeProperty(SCHOOL_SCORE_PROPERTY, schoolScore);
    }
    public Integer getSchoolScore() {
        return (Integer)readProperty(SCHOOL_SCORE_PROPERTY);
    }

    public void setEvent(Event event) {
        setToOneTarget(EVENT_PROPERTY, event, true);
    }

    public Event getEvent() {
        return (Event)readProperty(EVENT_PROPERTY);
    }


}
