package org.example.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.example.cayenne.persistent.Division;

/**
 * Class _School was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _School extends CayenneDataObject {

    public static final String CLASS_TYPE_PROPERTY = "classType";
    public static final String NAME_PROPERTY = "name";
    public static final String DIVISION_PROPERTY = "division";

    public static final String ID_PK_COLUMN = "ID";

    public void setClassType(String classType) {
        writeProperty(CLASS_TYPE_PROPERTY, classType);
    }
    public String getClassType() {
        return (String)readProperty(CLASS_TYPE_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setDivision(Division division) {
        setToOneTarget(DIVISION_PROPERTY, division, true);
    }

    public Division getDivision() {
        return (Division)readProperty(DIVISION_PROPERTY);
    }


}
