package org.example.cayenne.persistent.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Scores was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Scores extends CayenneDataObject {

    public static final String EVENT_ID_PROPERTY = "eventId";
    public static final String SCHOOL_ID_PROPERTY = "schoolId";
    public static final String SCORE_PROPERTY = "score";

    public static final String ID_PK_COLUMN = "ID";

    public void setEventId(Integer eventId) {
        writeProperty(EVENT_ID_PROPERTY, eventId);
    }
    public Integer getEventId() {
        return (Integer)readProperty(EVENT_ID_PROPERTY);
    }

    public void setSchoolId(Integer schoolId) {
        writeProperty(SCHOOL_ID_PROPERTY, schoolId);
    }
    public Integer getSchoolId() {
        return (Integer)readProperty(SCHOOL_ID_PROPERTY);
    }

    public void setScore(Integer score) {
        writeProperty(SCORE_PROPERTY, score);
    }
    public Integer getScore() {
        return (Integer)readProperty(SCORE_PROPERTY);
    }

}
